on:
  release:
    types: [published]

name: Cargo Publish

jobs:
  publish_crate:
    name: Cargo Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Publish crate
        run: |
          cargo publish --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish_cli_binary:
    name: Release build with ${{ matrix.os }}
    strategy:
      fail-fast: true
      # TODO: Not sure I agree with this setup of different runners; seems like we should use cross or something
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Rust Stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-auditable
        run: cargo install cargo-auditable cargo-audit

      - name: Build
        run: cargo auditable build --release

      - name: Push Artifacts
        run: |
          mv target/release/b2get target/release/b2get.${{ matrix.target }}
          gh release upload ${{ github.event.release.tag_name }} target/release/b2get.${{ matrix.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
